---
- name: Configure Apache Servers
  remote_user: ravi
  hosts: apache
  become: yes

  roles:
    - apache
    - java

- name: Configure Nginx Servers
  hosts: nginx
  become: yes

  roles:
    - nginx
